CREATE TABLE IF NOT EXISTS `posts` (
  `ID` INTEGER PRIMARY KEY AUTOINCREMENT,
  `author_id` INTEGER NOT NULL DEFAULT '0',
  `created` TEXT NOT NULL DEFAULT '0000-00-00 00:00:00',
  `content` TEXT NOT NULL,
  `title` TEXT NOT NULL,
  `tag` TEXT NOT NULL DEFAULT ''
);